CREATE TABLE `account` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) DEFAULT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE `book`;
CREATE TABLE `book` (
  `id` BIGINT(22) NOT NULL,
  `isbn10` BIGINT(22) NOT NULL,
  `isbn13` BIGINT(22) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `publisher` VARCHAR(255) NOT NULL,
  `pubdate` DATETIME NOT NULL DEFAULT "2000-01-01 00:00:00",
  `pages` BIGINT(10) NOT NULL,
  `price` VARCHAR(255) NOT null DEFAULT "",
  `image` VARCHAR(255) DEFAULT NULL,
  `alt` VARCHAR(255) DEFAULT NULL,
  `owner_id` BIGINT(22) NOT NULL,
  `owner_name` VARCHAR(255) NOT NULL,
  `borrower_id` BIGINT(22) NOT NULL,
  `borrower_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tag` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `count` BIGINT(22) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `category` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent_id` BIGINT(22) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;